[package]
name = "tower_governor"
authors = ["Ben Wishovich <ben@benw.is>"]
description = "A rate-limiting middleware for Tower backed by the governor crate that allows configurable key based and global limits"
repository = "https://github.com/benwis/tower-governor"
license = "MIT OR Apache-2.0"
readme = "README.md"
version = "0.2.0"
edition = "2021"
keywords = ["axum", "tower", "tonic", "rate-limit", "governor"]
categories = ["web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5"
forwarded-header-value = "0.1.1"
futures = "0.3.25"
futures-core = "0.3.25"
governor = "0.6.0"
http = "1.0.0"
pin-project = "1.0.12"
thiserror = "1.0.37"
tokio = { version = "=1.14", features = ["full"] }
tower = "0.4.13"
tower-layer = "0.3.2"
tracing = { version = "0.1.37", features = ["attributes"] }

[dev-dependencies]
hyper = "=0.14.27"
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.89"
tower-http = { version = "0.5", features = ["trace"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[features]
# Enables tracing output for this middleware
tracing = []
